[package]
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
description = "Neotron BMC firmware to run on the STM32F030 on the Neotron Pico"
edition = "2018"
license = "GPL-3.0-or-later"
name = "neotron-bmc-pico"
readme = "README.md"
version = "0.5.3"

[dependencies]
cortex-m = { version = "0.7.5", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rtic = "1.0"
debouncr = "0.2"
defmt = "0.3"
defmt-rtt = "0.4"
heapless= "0.7"
panic-probe = { version = "0.3", features = ["print-defmt"] }
stm32f0xx-hal = { version = "0.18", features = ["stm32f030x6", "rt"] }
neotron-bmc-protocol = { version = "0.1", path = "../neotron-bmc-protocol", features = ["defmt"] }
neotron-bmc-commands = { version = "0.1", path = "../neotron-bmc-commands" }
systick-monotonic = "1.0"
embedded-hal = "*"

[features]
# set logging levels here
default = [
  "defmt-default",
]
# You need to enable one of these two
stm32f030x6 = [ "stm32f0xx-hal/stm32f030x6"]
stm32f031 = [ "stm32f0xx-hal/stm32f031"]

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false
