name: Format

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add Tool
      run: rustup component add rustfmt
    - name: Check format neotron-bmc-pico
      run: cd neotron-bmc-pico && cargo fmt -- --check
    - name: Check format neotron-bmc-nucleo
      run: cd neotron-bmc-nucleo && cargo fmt -- --check
    - name: Check format neotron-bmc-protocol
      run: cd neotron-bmc-protocol && cargo fmt -- --check
    - name: Check format neotron-bmc-commands
      run: cd neotron-bmc-commands && cargo fmt -- --check
